version: '3'

services:
  mysql-user:
    image: mysql:5.7
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
      MYSQL_USER: consoleUser
      MYSQL_PASSWORD: qwe123!@
    ports:
      - "3307:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 30s

  mysql-alert:
    image: mysql:5.7
    container_name: mysql-alert
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alert-service
      MYSQL_USER: consoleUser
      MYSQL_PASSWORD: qwe123!@
    ports:
      - "3308:3306"
    volumes:
      - mysql-alert-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 30s

  mysql-weather:
    image: mysql:5.7
    container_name: mysql-weather
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather-service
      MYSQL_USER: consoleUser
      MYSQL_PASSWORD: qwe123!@
    ports:
      - "3309:3306"
    volumes:
      - mysql-weather-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
#      start_period: 30s

  mongo-location:
    container_name: mongo-location
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-location-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
#      start_period: 40s

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: weather-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  discovery-server:
    image: paovan/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "eureka:password", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    image: paovan/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8181:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/spring-boot-microservices-realm
    depends_on:
      discovery-server:
        condition: service_healthy

  weather-service:
    container_name: weather-service
    image: paovan/weather-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-weather:3306/weather-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    depends_on:
      mysql-weather:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    restart: unless-stopped

  location-service:
    container_name: location-service
    image: paovan/location-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongo-location:27017/location-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      KAFKA_TOPICS_WEATHER_ALERTS: weather-alerts
      WEATHER_THRESHOLDS_WIND_SPEED: 20.0
      WEATHER_THRESHOLDS_HIGH_TEMP: 35.0
      WEATHER_THRESHOLDS_LOW_TEMP: -10.0
      WEATHER_THRESHOLDS_PRECIPITATION: 50.0
    depends_on:
      mongo-location:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      kafka:
        condition: service_started
    restart: unless-stopped

  user-service:
    container_name: user-service
    image: paovan/user-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/user-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      mysql-user:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    restart: unless-stopped

  alert-service:
    container_name: alert-service
    image: paovan/alert-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-alert:3306/alert-service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:password@discovery-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICES_USER_SERVICE_URL: http://user-service:8080
    depends_on:
      mysql-alert:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      kafka:
        condition: service_started
      user-service:
        condition: service_started
    restart: unless-stopped

volumes:
  mysql-user-data:
  mysql-alert-data:
  mysql-weather-data:
  mongo-location-data: